import click
from storage import load_data, save_data
from utility import pluralize

@click.group(help="Commands for managing and viewing products and its categories.")
def products():
    """Product and its categories management commands."""
    pass

@products.command(help="List all unique categories.")
def list_categories():
    """Lists all the unique categories based on past orders."""
    categories = []

    data = load_data()
    orders = data.get("orders", {})

    for cust_orders in orders.values():
        categories.extend([category for product, price, category in cust_orders])

    uniq_categories = list(set(categories))

    word = pluralize(len(uniq_categories), "category", "categories")
    print(f"Here is the list of unique {word}: {uniq_categories}")

@products.command(help="Show total revenue per product category.")
def revenue_per_category():
    """Calculates and displays the total revenue generated by each category."""
    categories = {}

    data = load_data()
    orders = data.get("orders", {})

    if not orders:
        print("No orders found to calculate revenue.")
        return

    for cust_orders in orders.values():
        for product, price, category in cust_orders:
            categories[category] = categories.get(category, 0) + price

    print(f"Revenue per category: {categories}")

@products.command(name='list', help="List all unique products.")
def show():
    """Shows a list of all unique products that have been ordered."""
    products_list = []

    data = load_data()
    orders = data.get("orders", {})

    for cust_orders in orders.values():
        products_list.extend([product for product, price, category in cust_orders])

    uniq_products = list(set(products_list))

    word = pluralize(len(uniq_products), "product")
    print(f"Here is the list of unique {word}: {uniq_products}")
